In [ ]:
import math
import numpy as np
width,height=640,480
pos=[width/2.0,height/2.0]+10*np.random.rand(N*2).reshape(N,2)
angles=2*math.pi*np.random.rand(N)
vel=np.array(list(zip(np.sin(angles),np.cos(anglesles))))


In [7]:
import math
import numpy as np
width,height,N=640,480,10
#rand（0,1）平均取值-0.5所以是（-0.5,0.5）
pos=[width/2.0,height/2.0]+10*(np.random.rand(N*2)-0.5).reshape(N,2)
#边界条件
def applyBC(self):
    deltaR=2.0
    for coord in self.pos:
        if coord[0]>width+deltaR:
            coord[0]=-deltaR
        if coord[0]<-deltaR:
            coord[0]=width+deltaR
        if coord[1]>height+deltaR:
            coord[1]=-deltaR
        if coord[1]<-detaR:
            coord[1]=height+deltaR
#利用matplotlib绘制类鸟群
fig=plt.figure()
ax=plt.axes(xlim=(0,width),ylim=(0,height))
#头
pts,=ax.plot([],[],markersize=10,c='k',marker='o',ls='None')
#喙
beak,=ax.plot([],[],markersize=4,c='r',marker='o',ls='None')
#看不懂（添加鼠标按钮事件）
anim=animation.FuncAnimation(fig,tick,fargs=(pts,beak,boids),interval=50)
#头部的位置，10个单位
vec=self.pos+10*self.vel/self.maxVel
#更新reshape,轴set_data,偶数元素（x轴的值），奇数元素（y轴的值）
beak.set_data(vec.reshape(2*self.N)[::2], vec.reshape(2*self.N)[1::2])
import numpy as np
from scipy.spatial.distance import squareform,pdist,cdist
def test2(pos,radius):
    #距离阵列看不懂,计算每两点之间的距离
    distMatrix=squareform(pdist(pos))
    #应用规则
    D=distMatrix<radius
    #计算速度
    vel=pos*D.sum(axis=1).reshape(N,1)-D.dot(pos)
    return vel
    



[[319.92776225 244.2739016 ]
 [323.77880757 238.5825984 ]
 [318.42779269 241.61490916]
 [323.1626958  242.72209057]
 [320.07694634 241.37351323]
 [320.38691286 240.82463557]
 [323.19166383 244.57453607]
 [322.33605913 242.8164477 ]
 [318.97076344 238.99240618]
 [317.99855093 242.25682724]]


In [41]:
import numpy as np
from scipy.spatial.distance import squareform,pdist

x=np.array([[0.0,0.0],[1.0,1.0],[2.0,2.0]])
pos=np.array([5])
distMatrix=squareform(pdist(x))
print("--------------------------")
print("--------------------------")
print("--------------------------")
print(distMatrix)
print("--------------------------")
print("--------------------------")
print("--------------------------")
print(distMatrix.sum())
print("--------------------------")
print("--------------------------")
print("----axis=1是横着加--------")
print(distMatrix.sum(axis=1))
print("--------------------------")
print("--------------------------")
print("----axis=0是竖着加--------")
print(distMatrix.sum(axis=0))
print("--------------------------")
print("--------------------------")
print("--------------------------")
D=distMatrix<1.4
print(D)
print("--------------------------")
print("--------------------------")
print("--------------------------")
print(D.sum(axis=1))
print("--------------------------")
print("--------------------------")
print("--------------------------")
print(distMatrix.sum(axis=1).dot(pos))
#pos*D.sum(axis=1).reshape(N,1)-D.dot(pos)

--------------------------
--------------------------
--------------------------
[[0.         1.41421356 2.82842712]
 [1.41421356 0.         1.41421356]
 [2.82842712 1.41421356 0.        ]]
--------------------------
--------------------------
--------------------------
11.313708498984761
--------------------------
--------------------------
----axis=1是横着加--------
[4.24264069 2.82842712 4.24264069]
--------------------------
--------------------------
----axis=0是竖着加--------
[4.24264069 2.82842712 4.24264069]
--------------------------
--------------------------
--------------------------
[[ True False False]
 [False  True False]
 [False False  True]]
--------------------------
--------------------------
--------------------------
[1 1 1]
--------------------------
--------------------------
--------------------------


ValueError: shapes (3,) and (1,) not aligned: 3 (dim 0) != 1 (dim 0)